[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_tweets = "Gns3vGyjsn9L8jticbLGBug1rwm9qrUJCuHETPCHbfig"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
